# Welcome to Jekyll!

# Site settings

# These are used to personalize your new site.
title: Neda Azarmehr
email: n.azarmehr@sheffield.ac.uk
description: >-
  Assistant Professor in Data Science and AI. My research focuses on machine learning,
  computer vision, medical imaging, and trustworthy AI in healthcare.
twitter_username: AzarmehrN
github_username: nedaazarmehr
minimal_mistakes_skin: default
search: true

# Header navigation menu
header_pages:
  - projects.md
  - publications.md

# Sidebar settings
theme: minimal-mistakes-jekyll
sidebar:
  nav: null

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/London
include:
  - _pages
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name   : "Neda Azarmehr"
  avatar : "/assets/images/profile.jpg"
  bio    : "Assistant Professor in Data Science and AI. My research focuses on machine learning, deep learning, and trustworthy AI in healthcare applications."
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=YOUR_ID"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/YOUR-ORCID-ID"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Neda-Azarmehr"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/AzarmehrN"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nedaazarmehr"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:n.azarmehr@sheffield.ac.uk"

# Footer links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/AzarmehrN"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nedaazarmehr"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
