# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Neda Azarmehr
email: n.azarmehr@sheffield.ac.uk
header_pages:
  - Publications.md
  - Projects.md
sidebar:
  nav: null
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "First Lastname"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I’m an Assistant Professor in Data Science and AI at the University of Sheffield. I completed my PhD in Computer Science in 2021 at the University of Lincoln, with a focus on Artificial Intelligence, in collaboration with Imperial College London.
Following my PhD, I worked as a Postdoctoral Research Fellow at the University of Sheffield. My research lies at the intersection of AI, computer vision, and healthcare, with a strong focus on medical imaging and decision support systems. I’ve developed models for echocardiography view classification, left ventricle segmentation, speckle tracking, colonic polyp detection, and cancer pathology image analysis.
I am particularly passionate about trustworthy AI, working to ensure algorithmic fairness, interpretability, and ethical robustness. My broader goal is to develop AI tools that are not only technically accurate but also equitable, explainable, and clinically useful.
I am a Fellow of the Higher Education Academy and a Royal Academy of Engineering Awardee.
."
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=YOUR_ID"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/YOUR-ORCID-ID"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Neda-Azarmehr"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/AzarmehrN"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nedaazarmehr"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:n.azarmehr@sheffield.ac.uk"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NdaAzr"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
